spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/foodiehub
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      repositories:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-SECRET}
            scope: email, profile
            redirect-uri: http://localhost:8081/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 8081

food:
  service:
    url: http://localhost:8082

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  email: ${ADMIN_EMAIL:admin@foodiehub.com}

jwt:
  secret:
    key: ${JWT_KEY}
  token:
    expiration: ${JWT_EXPIRATION}

refresh:
  token:
    expiration: ${REFRESH_TOKEN_EXPIRATION}

logging:
  level:
    org.springframework.security: DEBUG