spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: user-service-auth
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/auth/**

          - id: user-service-users
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/user, /api/v1/user/**

          - id: user-service-refresh
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/refresh-token/**

          - id: user-service-oauth2
            uri: http://localhost:8081
            predicates:
              - Path=/oauth2/**, /login/oauth2/**

          - id: user-service-contact
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/contact

          - id: user-service-admin-contact-messages
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/admin/contact-messages, /api/v1/admin/contact-messages/**

          - id: food-service-slides-public
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/slides

          - id: food-service-slides-admin
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/admin/slides, /api/v1/admin/slides/**

          - id: food-service-admin-restaurants
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/admin/restaurants, /api/v1/admin/restaurants/**

          - id: user-service-admin-users
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/admin/users, /api/v1/admin/users/**

          - id: user-service-activity-logs
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/admin/activity-logs

          - id: user-service-restaurant-owners
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/admin/restaurant-owners, /api/v1/admin/restaurant-owners/**

          - id: user-service-drivers
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/admin/drivers, /api/v1/admin/drivers/**

          - id: notification-service-notifications
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/admin/notifications, /api/v1/admin/notifications/**

          - id: notification-service-push-subscription
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/admin/push-subscription

          - id: user-service-partner
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/partner/**

          - id: user-service-driver-register
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/driver/**

          - id: food-service-restaurants
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/restaurants, /api/v1/restaurants/**

          - id: food-service-cuisines
            uri: http://localhost:8082
            predicates:
              - Path=/api/cuisines/**

          - id: food-service-search
            uri: http://localhost:8082
            predicates:
              - Path=/api/search/**

          - id: order-service-cart
            uri: http://localhost:8083
            predicates:
              - Path=/api/cart/**

          - id: order-service-orders
            uri: http://localhost:8083
            predicates:
              - Path=/api/orders/**

          - id: order-service-payments
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/payments/**

          - id: notification-service-restaurant
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/restaurant/notifications, /api/v1/restaurant/notifications/**

          - id: notification-service-customer
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/customer/notifications, /api/v1/customer/notifications/**, /api/v1/customer/push-subscription


server:
  port: 8080

jwt:
  secret:
    key: ${JWT_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
