server:
  port: 8083

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodiehub_food
      auto-index-creation: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
